### PR TITLE
added children handling by Avatar

### PR DESCRIPTION
**Pull request by NoWay1201**
Hello,

I needed Avatar to render a Text for me, not only image or Icon, so I added this feature. It's taking Text to render as a children. Text is rendered only when there is no image or icon.

### CODE REVIEW

**Comment by Salakar** [comment]
Good idea, is it worth probably renaming `children` to `text` as by the looks of it, it's just text to render in a textview.

@Ehesp thoughts?

**Comment by NoWay1201** [comment]
@Salakar I was thinking about it, but I decided to not passing it to Avatar like this:
```
<Avatar size={this.props.size} color={frontColor} backgroundColor={color} children={'my rendered text'}/>;
```
but like this:
```
<Avatar size={this.props.size} color={frontColor} backgroundColor={color}>my rendered text</Avatar>;
```

**Comment by Ehesp** [comment]
@NoWay1201 cheers - I think having it as a prop would be better as it's more explicit and also other components follow the same pattern then?

**Comment by NoWay1201** [comment]
@Ehesp I was following the material-ui implementation, but it's not a problem, commited it with the 'text' prop. :)

**Comment by Salakar** [comment]
thanks for that @NoWay1201 - all merged!

**Pull request merged**
