### PR TITLE
Fixing Drawer/checkbox style broken on react-native 0.3*

### PR DESCRIPTION
**Pull request by renanccastro**
I was using this plugin in react-native 0.30.0, but the drawer and it's sections was broken, same with checkbox and radiobuttons. Fixed on this commit. Just some style fix.

### CODE REVIEW

**Comment by mlabrum** [comment]
could we get a before/after screenshot?

**Comment by renanccastro** [comment]
@mlabrum 
**Before:**
captura de tela 2016-08-16 as 23 55 06
captura de tela 2016-08-16 as 23 54 54

**After:**
captura de tela 2016-08-16 as 23 56 55
captura de tela 2016-08-16 as 23 56 48

**Comment by Tim-W** [comment]
👍

**Comment by mlabrum** [comment]
@Ehesp any chance we could get this merged?

**Pull request merged**
