### PR TITLE
Add missing semicolons

### PR DESCRIPTION
**Pull request by zoontek**
Hi,

Just a quick PR to merge quickly if possible to ensure react-native 0.18 compatibility for the moment (the error messages are not clear on this release) :)

### CODE REVIEW

**Comment by Ehesp** [comment]
Thanks, I won't be able to publish for an hour or so though, unless
@salakar is around.

**Comment by zoontek** [comment]
No worry, one hour is really quick! (I was thinking in days)

**Comment by Salakar** [comment]
I've merged it but have no permission to publish on npm atm, will have to wait for @Ehesp

**Comment by Salakar** [comment]
Published!

**Pull request merged**
